defaults:
  - /backbone: afroxlmr_large
  - /adapter: pfeiffer_rf16
  - /data: ta_ner
  - _self_

task_type: ner
la_path: ${ckpt_dir}/la_swh
da_path: ${ckpt_dir}/da_eng_bio_on_base
num_epochs: 10.0
batch_size: 16
grad_accum: 1
lr: 5.0e-5
max_length: 256
